#!/bin/sh
#
# build jingle
#

XFLAGS="-Xlint -Xlint:-serial"

#
# run
# ./build pmd
# to use this, and it should pass
#
# new PMD version has rulesets
#
PMDRULES="imports typeresolution clone finalizers sunsecure unusedcode braces migrating strictexception design"
PMDCATRULES="security bestpractices"

case $1 in
clean)
	rm -f `find uk/co -type f -name '*.class'`
	rm -f `find . -type f -name '*~'`
	rm -fr javadoc
	exit 0
	;;
pmd)
	RULESETS=""
	for RULE in $PMDRULES
	do
	    RULESETS="${RULESETS},rulesets/java/${RULE}.xml"
	done
	for RULE in $PMDCATRULES
	do
	    RULESETS="${RULESETS},category/java/${RULE}.xml"
	done
	RULESETS=`echo $RULESETS|sed s:,::`
	pmd -d uk -R $RULESETS -version 1.5 -auxclasspath `echo lib/java/* | sed 's= =:=g'` 2>/dev/null
	exit 0
	;;
doc)
	rm -fr javadoc
	mkdir javadoc
	javadoc -d javadoc uk.co.petertribble.jstripchart
	exit 0
	;;
esac

if [ -x /opt/onbld/bin/jstyle ]; then
    /opt/onbld/bin/jstyle `find uk -name '*.java'`
fi

javac ${XFLAGS} uk/co/petertribble/jstripchart/*.java

jar cf lib/java/jstripchart.jar `find uk/co/petertribble/jstripchart -type f -name '*.class'`
