#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# Copyright 2025 Peter Tribble
#
# build jstripchart
#

PATH=/usr/jdk/instances/jdk1.8.0/bin:$PATH
export PATH

#
# new PMD version 7 only has categories, configured in pmd-ruleset.xml
#
PMDRULES="./pmd-ruleset.xml"
PMDCACHE="${HOME}/.pmd/cache.jstripchart"

case $1 in
clean)
	rm -f $(find uk/co -type f -name '*.class')
	rm -f $(find . -type f -name '*~')
	rm -fr javadoc
	exit 0
	;;
pmd)
	if [ ! -d "${HOME}/.pmd" ]; then
	    mkdir -p "${HOME}/.pmd"
	fi
	pmd check --cache "${PMDCACHE}" -d uk -R "${PMDRULES}" --use-version java-1.8 2>/dev/null
	exit 0
	;;
javadoc)
	rm -fr javadoc
	mkdir javadoc
	javadoc -d javadoc uk.co.petertribble.jstripchart
	exit 0
	;;
esac

javac -Xlint uk/co/petertribble/jstripchart/*.java

jar cf lib/java/jstripchart.jar uk/co/petertribble/jstripchart/*.class
